openapi: 3.0.0
info:
  title: Physical AI & Humanoid Robotics Textbook API
  description: API for interactive features of the Physical AI & Humanoid Robotics textbook
  version: 1.0.0

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                name:
                  type: string
                password:
                  type: string
                  minLength: 8
              required:
                - email
                - name
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
                  createdAt:
                    type: string
                    format: date-time

  /api/auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

  /api/content/search:
    post:
      summary: Search textbook content using RAG
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                context:
                  type: string
                  description: Context for the search (e.g., current chapter)
              required:
                - query
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchResult'
                  query:
                    type: string
                  context:
                    type: string

  /api/progress:
    get:
      summary: Get user progress
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User progress data
          content:
            application/json:
              schema:
                type: object
                properties:
                  progress:
                    type: array
                    items:
                      $ref: '#/components/schemas/Progress'
    post:
      summary: Update user progress
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Progress'
      responses:
        '200':
          description: Progress updated successfully

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        role:
          type: string
          enum: [student, instructor, admin]
        preferences:
          type: object
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - email
        - name

    SearchResult:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        source:
          type: string
        score:
          type: number
          format: float

    Progress:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        chapterId:
          type: string
        completed:
          type: boolean
        completionDate:
          type: string
          format: date-time
        timeSpent:
          type: number
        quizResults:
          type: array
          items:
            type: object

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT